// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DownloadAlbum(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ScanArtist(arg1:string):Promise<Array<models.Album>>;

export function SelectFolder():Promise<string>;

export function StopScan():Promise<void>;
