// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadAlbum(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadAlbum'](arg1, arg2, arg3);
}

export function ScanArtist(arg1) {
  return window['go']['main']['App']['ScanArtist'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StopScan() {
  return window['go']['main']['App']['StopScan']();
}
